// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EncodingConverter
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EncodingConverterString = "71a14b6d-876d-4268-b7ff-27ccc377c788";
        public static Guid EncodingConverter = new Guid(EncodingConverterString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ProjectRightClickGroup = 0x0003;
        public const int ConvertProjectCommand = 0x0002;
        public const int FileRightClickGroup = 0x0001;
        public const int ConvertFileCommand = 0x0100;
    }
}